version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: pharmos_db
      POSTGRES_USER: pharmos_user
      POSTGRES_PASSWORD: pharmos_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  elasticsearch:
    image: elasticsearch:8.11.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
      - mongodb
      - redis
    volumes:
      - ./src:/app/src
      - ./config:/app/config

  ml-service:
    build:
      context: .
      dockerfile: Dockerfile.ml
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres
      - redis
    volumes:
      - ./ml:/app/ml
      - ./src/api:/app/src/api

volumes:
  postgres_data:
  mongo_data:
  redis_data:
  es_data:
