apiVersion: apps/v1
kind: Deployment
metadata:
  name: pharmos-backend
  namespace: pharmos
  labels:
    app.kubernetes.io/name: pharmos-backend
    app.kubernetes.io/part-of: pharmos-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: pharmos-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pharmos-backend
        app.kubernetes.io/part-of: pharmos-platform
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: backend
        image: pharmos/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: pharmos-config
              key: NODE_ENV
        - name: POSTGRES_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)"
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: pharmos-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pharmos-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: pharmos-config
              key: POSTGRES_DB
        - name: MONGODB_URL
          value: "mongodb://mongodb:27017/$(MONGODB_DB)"
        - name: MONGODB_DB
          valueFrom:
            configMapKeyRef:
              name: pharmos-config
              key: MONGODB_DB
        - name: REDIS_URL
          value: "redis://redis:6379/$(REDIS_DB)"
        - name: REDIS_DB
          valueFrom:
            configMapKeyRef:
              name: pharmos-config
              key: REDIS_DB
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: pharmos-secrets
              key: JWT_SECRET
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: pharmos-backend
  namespace: pharmos
  labels:
    app.kubernetes.io/name: pharmos-backend
    app.kubernetes.io/part-of: pharmos-platform
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app.kubernetes.io/name: pharmos-backend
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pharmos-backend-ingress
  namespace: pharmos
  labels:
    app.kubernetes.io/name: pharmos-backend
    app.kubernetes.io/part-of: pharmos-platform
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: api.pharmos.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pharmos-backend
            port:
              number: 3000