global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'pharmos'
    replica: 'pharmos-prometheus'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Node.js Backend API
  - job_name: 'pharmos-backend'
    static_configs:
      - targets: ['backend:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    labels:
      service: 'backend'
      environment: 'development'

  # Python ML Service
  - job_name: 'pharmos-ml-service'
    static_configs:
      - targets: ['ml-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s
    labels:
      service: 'ml-service'
      environment: 'development'

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: '/metrics'
    scrape_interval: 30s
    labels:
      service: 'postgres'
      environment: 'development'

  # MongoDB
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    metrics_path: '/metrics'
    scrape_interval: 30s
    labels:
      service: 'mongodb'
      environment: 'development'

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    metrics_path: '/metrics'
    scrape_interval: 30s
    labels:
      service: 'redis'
      environment: 'development'

  # Elasticsearch
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
    metrics_path: '/metrics'
    scrape_interval: 30s
    labels:
      service: 'elasticsearch'
      environment: 'development'

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: '/metrics'
    scrape_interval: 15s
    labels:
      service: 'node-exporter'
      environment: 'development'

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s
    labels:
      service: 'cadvisor'
      environment: 'development'